# Generated by Django 4.1.1 on 2022-11-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_rights',
            field=models.CharField(choices=[('employee', 'Employee'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
