# Generated by Django 4.1.1 on 2022-11-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_rights',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('employee', 'Employee')], default='user', max_length=20),
        ),
    ]
