# Generated by Django 4.1.1 on 2022-11-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
    ]
